moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.14.0
project:
  name: moai-adk-go
  mode: personal
  description: ''
  created_at: '2026-02-03 12:16:52'
  template_version: 1.14.0
  optimized: false
